repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v4.4.0
        hooks:
            -   id: detect-aws-credentials
                args: [ "--allow-missing-credentials" ]
            -   id: detect-private-key
            -   id: check-added-large-files
            -   id: check-symlinks
            -   id: check-merge-conflict
            -   id: check-yaml
            -   id: debug-statements
    -   repo: https://github.com/PyCQA/flake8
        rev: 6.0.0
        hooks:
            -   id: flake8
                args: [ "--config", "setup.cfg" ]
